[workspace]
members = ["crates/*"]

[workspace.package]
description = "Pragma Oracle"
documentation = "https://www.pragma.build/"
cairo-version = "2.8.2"
version = "0.1.0"
readme = "README.md"
repository = "https://github.com/astraly-labs/pragma-monorepo"
license-file = "../LICENSE.md"

[workspace.dependencies]
starknet = "2.8.2"

# OpenZeppelin components & utilities
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", branch = "upgrade-edition-2024-07" }


# Alexandria (same version than Hyperlane)
# TODO: Update back to main repository once PR is merged:
# https://github.com/keep-starknet-strange/alexandria/pull/332
alexandria_bytes = { git = "https://github.com/maxdesalle/alexandria.git" }
alexandria_sorting = { git = "https://github.com/maxdesalle/alexandria.git" }
alexandria_storage = { git = "https://github.com/maxdesalle/alexandria.git" }
alexandria_math = { git = "https://github.com/maxdesalle/alexandria.git" }
cubit = { git = "https://github.com/dojoengine/cubit", branch = "cairo_2.7" }


# Pragma Oracle crates
pragma_oracle = { path = "crates/pragma_oracle" }
pragma_publisher_registry = { path = "crates/pragma_publisher_registry" }
pragma_summary_stats = { path = "crates/pragma_summary_stats" }
pragma_entry = { path = "crates/pragma_entry" }
pragma_operations = { path = "crates/pragma_operations" }

# Test dependencies
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.30.0" }

[workspace.tool.fmt]
sort-module-level-items = true
