[package]
name = "pragma_feeds_registry"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
openzeppelin_upgrades.workspace = true
starknet.workspace = true
alexandria_storage.workspace = true
openzeppelin_access.workspace = true
openzeppelin_governance.workspace = true
openzeppelin_security.workspace = true

pragma_feed_types.workspace = true

[tool]
fmt.workspace = true

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true

[lib]
name = "pragma_feeds_registry"

[dev-dependencies]
snforge_std.workspace = true

[scripts]
test = "snforge test --max-n-steps 4294967295"
test-profiling = "snforge test --max-n-steps 4294967295 --build-profile"
