[workspace]
members = ["crates/*"]

[workspace.package]
description = "Pragma Crosschain Dispatcher"
documentation = "https://www.pragma.build/"
cairo-version = "2.8.2"
version = "0.1.0"
readme = "README.md"
repository = "https://github.com/astraly-labs/pragma-monorepo"
license-file = "../LICENSE.md"

[workspace.dependencies]
starknet = "2.8.2"

# OpenZeppelin components & utilities
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.17.0" }

# Pragma Oracle
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib", rev = "86d7ccd" }

# Alexandria (same version than Hyperlane)
# TODO: Update back to main repository once PR is merged:
# https://github.com/keep-starknet-strange/alexandria/pull/332
alexandria_bytes = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "95d98a5" }

# Pragma Dispatcher crates
pragma_feed_types = { path = "crates/pragma_feed_types" }
pragma_feeds_registry = { path = "crates/pragma_feeds_registry" }
pragma_dispatcher = { path = "crates/pragma_dispatcher" }
pragma_maths = { path = "crates/pragma_maths" }

# Test dependencies
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.31.0" }

[workspace.tool.fmt]
sort-module-level-items = true
