[workspace]
name = "pragma_dispatcher"
version = "0.1.0"
edition = "2024_07"
members = ["crates/"]

[workspace.package]
description = "Pragma Dispatcher contracts - caller of the Pragma Oracle & Hyperlane contracts"
documentation = "https://www.pragma.build/"
cairo-version = "2.8.2"
version = "0.1.0"
readme = "README.md"
repository = "https://github.com/astraly-labs/pragma-monorepo"

[workspace.dependencies]
starknet = "2.8.2"

[workspace.tool.fmt]
sort-module-level-items = true
