[workspace]
name = "pragma_dispatcher"
version = "0.1.0"
edition = "2023_11"
members = ["crates/*"]

[workspace.package]
description = "Pragma Crosschain Dispatcher"
documentation = "https://www.pragma.build/"
cairo-version = "2.6.3"
version = "0.1.0"
readme = "README.md"
repository = "https://github.com/astraly-labs/pragma-monorepo"

[workspace.dependencies]
starknet = "2.6.3"

# OpenZeppelin components & utilities
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.14.0" }

# Hyperlane core contracts
hyperlane_starknet = { git = "https://github.com/astraly-labs/hyperlane_starknet.git", branch = "feat-token-extensions", rel_path = "cairo" }

# Pragma Dispatcher crates
pragma_feed_types = { path = "crates/pragma_feed_types" }
pragma_feed_registry = { path = "crates/pragma_feed_registry" }
pragma_dispatcher = { path = "crates/pragma_dispatcher" }
pragma_maths = { path = "crates/pragma_maths" }

# Test dependencies
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.22.0" }

[workspace.tool.fmt]
sort-module-level-items = true
