[package]
name = "pragma_feed_types"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet.workspace = true
alexandria_bytes.workspace = true

[tool]
fmt.workspace = true

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true

[lib]
name = "pragma_feed_types"

[dev-dependencies]
snforge_std.workspace = true

[scripts]
test = "snforge test --max-n-steps 4294967295"
test-profiling = "snforge test --max-n-steps 4294967295 --build-profile"
