# Configuration for the Pragma Oracle Cairo contracts
pragma_oracle:
  pairs:
    - "BTC/USD"
    - "ETH/USD"
  publishers:
    - name: "PRAGMA"
      address: "0x3bb306a004034dba19e6cf7b161e7a4fef64bc1078419e8ad1876192f0b8cd1"
      sources:
        - "ASCENDEX"
        - "BITSTAMP"
        - "CEX"
        - "COINBASE"
        - "DEFILLAMA"
        - "GEMINI"
        - "KAIKO"
        - "OKX"
        - "BINANCE"
        - "BYBIT"
        - "GECKOTERMINAL"
        - "STARKNET"
        - "PROPELLER"
        - "KUCOIN"
        - "BINANCE"
        - "HUOBI"
        - "BYBIT"
        - "INDEXCOOP"
        - "MEXC"
        - "GATEIO"
        - "EKUBO"
        - "DEXSCREENER"
    - name: "PRAGMA_MERKLE"
      address: "0x5e9e93c6235f8ae6c2f4f0069bd30753ec21b26fbad80cfbf5da2c1bc573d69"
      sources:
        - "DERIBIT"

# Configuration for the Pragma Dispatcher Cairo Contracts
pragma_dispatcher:
  pragma_oracle_address: "0x753034396b7e59f3579e2beba2f408dd2ed12974e054a1348234bea4b10bd30"
  hyperlane_mailbox_address: "0x41c20175af14a0bfebfc9ae2f3bda29230a0bceb551844197d9f46faf76d6da"

# Configuration for the Pragma Solidity EVM contract
# TODO: Adapt those values
pragma:
  data_source_emitters:
    - chain_id: 1
      address: "0x51298007E4e8A48d11B64D9361d6ED64f2B4309D"
    - chain_id: 2
      address: "0x51298007E4e8A48d11B64D9361d6ED64f2B4309D"
    - chain_id: 3
      address: "0x51298007E4e8A48d11B64D9361d6ED64f2B4309D"

  valid_time_period_in_seconds: 3600 # 1 hour
  single_update_fee_in_wei: "0.01" # 0.01 eth

  hyperlane:
    validators:
      - "0x1234567890123456789012345678901234567890"
      - "0x2345678901234567890123456789012345678901"
      - "0x3456789012345678901234567890123456789012"
