# Configuration for the Pragma Oracle Cairo contracts
pragma_oracle:
  pairs:
    - "BTC/USD"
    - "BTC/EUR"
    - "ETH/USD"
    - "WBTC/USD"
    - "WBTC/BTC"
    - "USDT/USD"
    - "USDC/USD"
    - "DAI/USD"
    - "SOL/USD"
    - "STRK/USD"
    - "LUSD/USD"
    - "WSTETH/USD"
    - "STETH/USD"
    - "NSTR/USD"
    - "LORDS/USD"
    - "ZEND/USD"
    - "EKUBO/USD"
  publishers:
    - name: "PRAGMA"
      address: "0x04b6eb40fb7b0119344ca0dffaa3cfd9ac97734a5b785dfda5e52bd7008205cb"
      sources:
        - "ASCENDEX"
        - "BITSTAMP"
        - "CEX"
        - "COINBASE"
        - "DEFILLAMA"
        - "GEMINI"
        - "KAIKO"
        - "OKX"
        - "BINANCE"
        - "BYBIT"
        - "GECKOTERMINAL"
        - "STARKNET"
        - "PROPELLER"
        - "KUCOIN"
        - "HUOBI"
        - "INDEXCOOP"
        - "MEXC"
        - "GATEIO"
        - "EKUBO"
        - "DEXSCREENER"

# Configuration for the Pragma Dispatcher Cairo Contracts
pragma_dispatcher:
  pragma_oracle_address: "0x7ed4f0171a29815651d276fbdabf4773485cebf1feb5640942be74380bc7572"
  hyperlane_mailbox_address: "0x064bb5e29a7e9fc67dedabb6d1c385050feef028563078daa9025dd8b218e596"

# Configuration for the Pragma Solidity EVM contract
pragma:
  data_source_emitters:
    - chain_id: 6363709
      address: "0x30e6665bda019371307edfebc413596903413337c5e8f06d2385144d126cf10"

  valid_time_period_in_seconds: 3600 # 1 hour
  single_update_fee_in_wei: "0"

  hyperlane:
    validators:
      - "0xF6311461A6d8b44cb3F62b2FCd47570A28443ca0"
