# Configuration for the Pragma Oracle Cairo contracts
pragma_oracle:
  pairs:
    - "BTC/USD"
    - "BTC/EUR"
    - "ETH/USD"
    - "WBTC/USD"
    - "WBTC/BTC"
    - "USDT/USD"
    - "USDC/USD"
    - "DAI/USD"
    - "SOL/USD"
    - "STRK/USD"
    - "LUSD/USD"
    - "WSTETH/USD"
    - "STETH/USD"
    - "NSTR/USD"
    - "LORDS/USD"
    - "ZEND/USD"
    - "EKUBO/USD"
  publishers:
    - name: "PRAGMA"
      address: "0x6b09c5cca7e5ef944dc3be7514cc1ae5a6e267f0f1f2b5520e90dc00aecf6e1"
      sources:
        - "ASCENDEX"
        - "BITSTAMP"
        - "CEX"
        - "COINBASE"
        - "DEFILLAMA"
        - "GEMINI"
        - "KAIKO"
        - "OKX"
        - "BINANCE"
        - "BYBIT"
        - "GECKOTERMINAL"
        - "STARKNET"
        - "PROPELLER"
        - "KUCOIN"
        - "HUOBI"
        - "INDEXCOOP"
        - "MEXC"
        - "GATEIO"
        - "EKUBO"
        - "DEXSCREENER"

# Configuration for the Pragma Dispatcher Cairo Contracts
pragma_dispatcher:
  pragma_oracle_address: "0x56c94b626e02c82bfe871b06181bdc56adcd78f4ce722fe3f7ae6845795d8a8"
  hyperlane_mailbox_address: "0x5bfb1a565a1fa2eb33c5d8e587a7aeb5e6846d3aadf9fecb529ace1e3457096"

# Configuration for the Pragma Solidity EVM contract
pragma:
  data_source_emitters:
    - chain_id: 6363709
      address: "0x04d997c57f63d509f483927ce74135a4e12de834144d9e90044ac03f6024267e"

  valid_time_period_in_seconds: 3600 # 1 hour
  single_update_fee_in_wei: "0"

  hyperlane:
    validators:
      - "0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65"
