# Contains the supported Feeds by Pragma.
feeds:
  - name: "BTC/USD: Spot Median"
    id: "0x4254432f555344"

  - name: "BTC/EUR: Spot Median"
    id: "0x4254432f455552"

  - name: "WBTC/BTC: Spot Median"
    id: "0x574254432f425443"

  - name: "ETH/USD: Spot Median"
    id: "0x4554482f555344"

  - name: "SOL/USD: Spot Median"
    id: "0x534f4c2f555344"

  - name: "USDT/USD: Spot Median"
    id: "0x555344542f555344"

  - name: "DAI/USD: Spot Median"
    id: "0x4441492f555344"

  - name: "USDC/USD: Spot Median"
    id: "0x555344432f555344"

  - name: "STRK/USD: Spot Median"
    id: "0x5354524b2f555344"

  - name: "LUSD/USD: Spot Median"
    id: "0x4c5553442f555344"

  - name: "WBTC/USD: Spot Median"
    id: "0x574254432f555344"

  - name: "WSTETH/USD: Spot Median"
    id: "0x5753544554482f555344"

  - name: "STETH/USD: Spot Median"
    id: "0x53544554482f555344"

  - name: "NSTR/USD: Spot Median"
    id: "0x4e5354522f555344"

  - name: "LORDS/USD: Spot Median"
    id: "0x4c4f5244532f555344"

  - name: "ZEND/USD: Spot Median"
    id: "0x5a454e442f555344"

  - name: "EKUBO/USD: Spot Median"
    id: "0x454b55424f2f555344"

# Contract Routers
asset_classes_routers:
  - name: "Crypto"
    contract: "AssetClassRouter"
    id: "0"

    feed_types_routers:
      - name: "Unique: Spot Median"
        contract: "FeedTypeUniqueRouter"
        id: "0"

      - name: "Unique: Perp Median"
        contract: "FeedTypeUniqueRouter"
        id: "1"

      - name: "Unique: Spot Mean"
        contract: "FeedTypeUniqueRouter"
        id: "2"
