# EVM Chains Configuration
# Contains RPC endpoints and Hyperlane contract addresses for supported networks

zircuit_testnet:
  rpc_url: "https://zircuit1-testnet.p2pify.com"
  hyperlane_address: "0x3634ae539bFA68c055C8A714438542766f14D192"
