name: Task - Test Cairo

permissions: read-all

on:
  workflow_dispatch:
  workflow_call:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Scarb
        uses: software-mansion/setup-scarb@v1

      - name: Build contracts
        working-directory: cairo
        run: scarb build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pragma-dispatcher-contracts-build
          path: cairo/target/dev

  tests-unit:
    runs-on: ubuntu-latest-16-cores
    steps:
      - uses: actions/checkout@v3
      - uses: foundry-rs/setup-snfoundry@v3
      - uses: software-mansion/setup-scarb@v1
      - run: scarb fmt --check
        working-directory: cairo
      - run: scarb build
        working-directory: cairo
      - run: scarb test
        working-directory: cairo
