name: Task - Test Cairo

permissions: read-all

on:
  workflow_dispatch:
  workflow_call:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-test:
    strategy:
      matrix:
        project: [dispatcher, oracle]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Scarb
        uses: software-mansion/setup-scarb@v1.4.0
        with:
          scarb-version: "2.8.2"

      - name: Build contracts
        working-directory: cairo/${{ matrix.project }}
        run: scarb build
        id: build

      - name: Set up Starknet Foundry
        uses: foundry-rs/setup-snfoundry@v3
        with:
          starknet-foundry-version: "0.30.0"

      - name: Run tests
        working-directory: cairo/${{ matrix.project }}
        run: snforge test
        id: test

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pragma-${{ matrix.project }}-contracts-build
          path: cairo/${{ matrix.project }}/target/dev
