---
name: Task - Linters

on:
  workflow_dispatch:
  workflow_call:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run prettier
        run: |-
          npx prettier --check .

  toml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout toml files
        uses: actions/checkout@v3
      - name: Run toml check
        run: npx @taplo/cli fmt --config ./taplo.toml --check
