---
name: Workflow - Pull Request

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]
  push:
    branches: [main]

jobs:
  linters:
    name: Run linters
    uses: ./.github/workflows/linters.yml

  rust_build:
    name: Build Rust project
    uses: ./.github/workflows/rust-build.yml

  linters_cargo:
    name: Run Cargo linters
    uses: ./.github/workflows/linters-cargo.yml
    needs: rust_build

  solidity_test:
    name: Run Solidity tests
    uses: ./.github/workflows/solidity-test.yml

  cairo_test:
    name: Run Cairo tests
    uses: ./.github/workflows/cairo-test.yml
