name: Build and Push Image
on:
    push:
      tags:
        - theoros-v*
env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository }}
permissions:
  contents: read
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          [theoros]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/theoros-v}" >> $GITHUB_OUTPUT

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./rust/theoros/Dockerfile
          build-args: |
            PACKAGE_NAME=${{ matrix.package }}
          platforms: linux/arm64, linux/amd64
          tags: ${{ env.REGISTRY_IMAGE }}/${{ matrix.package }}:${{ steps.get_version.outputs.VERSION }}
          push: true
      - name: Docker Logout
        if: always()
        run: docker logout    
