name: Task - Test Solidity

on:
  workflow_dispatch:
  workflow_call:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    env:
      working-directory: ./solidity
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        working-directory: ${{ env.working-directory }}
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        working-directory: ${{ env.working-directory }}
        run: |
          forge test -vvv
        id: test

      - name: Run Forge tests with gas report
        working-directory: ${{ env.working-directory }}
        run: |
          forge test --match-contract PragmaDecoderGasTest -vvv --gas-report > gas_report.txt
        id: test

      - name: Parse and display gas report
        working-directory: ${{ env.working-directory }}
        run: |
          echo "Gas Report Summary:" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          grep -A 6 "Gas used for" gas_report.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
        id: gas_report

      - name: Upload gas report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: gas-report
          path: ${{ env.working-directory }}/gas_report.txt
